# Generated by Django 4.2.6 on 2023-12-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_mylikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyLikes',
        ),
    ]
