# Generated by Django 4.2.6 on 2023-10-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_contact_user_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
